import {
  PipelineRun,
  PipelineDefinition,
  SystemHealth,
  Deployment,
  Organization,
  Project,
  LogEntry,
  Artifact,
  Secret,
} from '../apiClient';

export const DEMO_USER = {
  id: 'usr_demo_8820',
  email: 'demo@opspilot.io',
  name: 'Sarah Chen',
  role: 'ADMIN',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  isSuperAdmin: true,
  isDemo: true,
};

export const DEMO_ORGANIZATION: Organization = {
  id: 'org_demo_acme',
  name: 'Acme Cloud Platform',
  slug: 'acme-corp',
  status: 'ACTIVE',
  createdAt: new Date(Date.now() - 180 * 86400000).toISOString(),
};

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj_demo_stockflow',
    name: 'StockFlow SaaS Platform',
    slug: 'stockflow-saas',
    organizationId: 'org_demo_acme',
    description: 'Inventory management and automated order fulfillment platform',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'proj_demo_ai_engine',
    name: 'OpsPilot Intelligence Engine',
    slug: 'opspilot-ai',
    organizationId: 'org_demo_acme',
    description: 'Autonomous RCA root cause analyzer & real-time log ingestion',
    status: 'ACTIVE',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
];

export const DEMO_SYSTEM_HEALTH: SystemHealth = {
  totalOrganizations: 3,
  totalProjects: 12,
  totalEnvironments: 4,
  totalPipelineDefinitions: 5,
  totalPipelineRuns: 154,
  totalDeployments: 48,
  deploymentSuccessRate: 98.4,
};

export const DEMO_PIPELINES: PipelineDefinition[] = [
  {
    id: 'pip_demo_1',
    projectId: 'proj_demo_stockflow',
    name: 'stockflow-backend',
    slug: 'stockflow-backend',
    description: 'NestJS REST & GraphQL core microservice API',
    triggerType: 'WEBHOOK',
    triggerBranch: 'main',
    isActive: true,
    currentVersionNumber: 28,
    repositoryUrl: 'https://github.com/opspilot-org/stockflow-api',
    branch: 'main',
    status: 'SUCCESS',
    lastRunAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    successRate: 98.2,
    totalRuns: 68,
  },
  {
    id: 'pip_demo_2',
    projectId: 'proj_demo_ai_engine',
    name: 'opspilot-ai-service',
    slug: 'opspilot-ai-service',
    description: 'FastAPI Python vector search & LLM RCA parser',
    triggerType: 'WEBHOOK',
    triggerBranch: 'main',
    isActive: true,
    currentVersionNumber: 14,
    repositoryUrl: 'https://github.com/opspilot-org/ai-analysis-service',
    branch: 'main',
    status: 'RUNNING',
    lastRunAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    successRate: 100,
    totalRuns: 34,
  },
  {
    id: 'pip_demo_3',
    projectId: 'proj_demo_stockflow',
    name: 'frontend-next',
    slug: 'frontend-next',
    description: 'Next.js 16 App Router UI with SSR & Static Export',
    triggerType: 'WEBHOOK',
    triggerBranch: 'main',
    isActive: true,
    currentVersionNumber: 42,
    repositoryUrl: 'https://github.com/opspilot-org/frontend-next',
    branch: 'main',
    status: 'SUCCESS',
    lastRunAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    successRate: 96.8,
    totalRuns: 45,
  },
  {
    id: 'pip_demo_4',
    projectId: 'proj_demo_stockflow',
    name: 'payments-worker',
    slug: 'payments-worker',
    description: 'Stripe webhook listener & billing event queue worker (Go)',
    triggerType: 'MANUAL',
    triggerBranch: 'feat/stripe-v3',
    isActive: true,
    currentVersionNumber: 9,
    repositoryUrl: 'https://github.com/opspilot-org/payments-worker',
    branch: 'feat/stripe-v3',
    status: 'FAILED',
    lastRunAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    successRate: 85.0,
    totalRuns: 16,
  },
  {
    id: 'pip_demo_5',
    projectId: 'proj_demo_stockflow',
    name: 'auth-gateway',
    slug: 'auth-gateway',
    description: 'OAuth2 / OpenID Connect JWT Authentication Proxy (Rust)',
    triggerType: 'WEBHOOK',
    triggerBranch: 'main',
    isActive: true,
    currentVersionNumber: 18,
    repositoryUrl: 'https://github.com/opspilot-org/auth-gateway',
    branch: 'main',
    status: 'SUCCESS',
    lastRunAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    successRate: 100,
    totalRuns: 22,
  },
];

export const DEMO_RUNS: PipelineRun[] = [
  {
    id: 'run_demo_101',
    pipelineDefinitionId: 'pip_demo_1',
    status: 'RUNNING',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: 'e4f92a189c42b8e3',
    branch: 'main',
    startedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 2.5 * 60 * 1000).toISOString(),
    durationSeconds: 45,
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    pipelineName: 'stockflow-backend',
    repositoryUrl: 'https://github.com/opspilot-org/stockflow-api',
    jobs: [
      {
        id: 'job_1',
        pipelineRunId: 'run_demo_101',
        name: 'Lint & Audit',
        stage: 'test',
        status: 'SUCCESS',
        startedAt: new Date(Date.now() - 110000).toISOString(),
        finishedAt: new Date(Date.now() - 95000).toISOString(),
        durationSeconds: 15,
      },
      {
        id: 'job_2',
        pipelineRunId: 'run_demo_101',
        name: 'Unit & E2E Tests',
        stage: 'test',
        status: 'SUCCESS',
        startedAt: new Date(Date.now() - 95000).toISOString(),
        finishedAt: new Date(Date.now() - 40000).toISOString(),
        durationSeconds: 55,
      },
      {
        id: 'job_3',
        pipelineRunId: 'run_demo_101',
        name: 'Build Docker Image',
        stage: 'build',
        status: 'RUNNING',
        startedAt: new Date(Date.now() - 40000).toISOString(),
      },
    ],
  },
  {
    id: 'run_demo_102',
    pipelineDefinitionId: 'pip_demo_2',
    status: 'SUCCESS',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: '8b3c1d904e12f90a',
    branch: 'main',
    startedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 14.5 * 60 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 15.2 * 60 * 1000).toISOString(),
    durationSeconds: 32,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    pipelineName: 'opspilot-ai-service',
    repositoryUrl: 'https://github.com/opspilot-org/ai-analysis-service',
    jobs: [
      {
        id: 'job_21',
        pipelineRunId: 'run_demo_102',
        name: 'Pytest Suite',
        stage: 'test',
        status: 'SUCCESS',
        durationSeconds: 14,
      },
      {
        id: 'job_22',
        pipelineRunId: 'run_demo_102',
        name: 'Container Scan',
        stage: 'security',
        status: 'SUCCESS',
        durationSeconds: 8,
      },
      {
        id: 'job_23',
        pipelineRunId: 'run_demo_102',
        name: 'Deploy Staging',
        stage: 'deploy',
        status: 'SUCCESS',
        durationSeconds: 10,
      },
    ],
  },
  {
    id: 'run_demo_103',
    pipelineDefinitionId: 'pip_demo_3',
    status: 'SUCCESS',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: 'f371b45aa2918e77',
    branch: 'main',
    startedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 41.5 * 60 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 42.2 * 60 * 1000).toISOString(),
    durationSeconds: 28,
    createdAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    pipelineName: 'frontend-next',
    repositoryUrl: 'https://github.com/opspilot-org/frontend-next',
  },
  {
    id: 'run_demo_104',
    pipelineDefinitionId: 'pip_demo_4',
    status: 'FAILED',
    triggerType: 'MANUAL',
    triggeredBy: 'Sarah Chen',
    commitSha: 'a345242ff1082c31',
    branch: 'feat/stripe-v3',
    startedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 1.95 * 3600 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 2.01 * 3600 * 1000).toISOString(),
    durationSeconds: 18,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    pipelineName: 'payments-worker',
    repositoryUrl: 'https://github.com/opspilot-org/payments-worker',
    jobs: [
      {
        id: 'job_41',
        pipelineRunId: 'run_demo_104',
        name: 'Go Test Suite',
        stage: 'test',
        status: 'SUCCESS',
        durationSeconds: 6,
      },
      {
        id: 'job_42',
        pipelineRunId: 'run_demo_104',
        name: 'Stripe API Mock Test',
        stage: 'integration',
        status: 'FAILED',
        durationSeconds: 12,
      },
    ],
  },
  {
    id: 'run_demo_105',
    pipelineDefinitionId: 'pip_demo_5',
    status: 'SUCCESS',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: '7c9e01fb4a9018e4',
    branch: 'main',
    startedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 4.9 * 3600 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 5.01 * 3600 * 1000).toISOString(),
    durationSeconds: 24,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    pipelineName: 'auth-gateway',
    repositoryUrl: 'https://github.com/opspilot-org/auth-gateway',
  },
  {
    id: 'run_demo_106',
    pipelineDefinitionId: 'pip_demo_1',
    status: 'SUCCESS',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: '5b2d8e411c8812f0',
    branch: 'main',
    startedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 7.9 * 3600 * 1000).toISOString(),
    durationSeconds: 39,
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    pipelineName: 'stockflow-backend',
    repositoryUrl: 'https://github.com/opspilot-org/stockflow-api',
  },
  {
    id: 'run_demo_107',
    pipelineDefinitionId: 'pip_demo_2',
    status: 'QUEUED',
    triggerType: 'SCHEDULED',
    triggeredBy: 'cron-job',
    commitSha: '9d1f3b2077182e90',
    branch: 'staging',
    queuedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    pipelineName: 'opspilot-ai-service',
    repositoryUrl: 'https://github.com/opspilot-org/ai-analysis-service',
  },
];

export const DEMO_LOGS: LogEntry[] = [
  {
    id: 'log_1',
    pipelineRunId: 'run_demo_104',
    level: 'INFO',
    message: 'Starting job "Stripe API Mock Test"...',
    timestamp: new Date(Date.now() - 1.99 * 3600 * 1000).toISOString(),
  },
  {
    id: 'log_2',
    pipelineRunId: 'run_demo_104',
    level: 'INFO',
    message: 'Connecting to Stripe Mock Server at http://localhost:12111',
    timestamp: new Date(Date.now() - 1.98 * 3600 * 1000).toISOString(),
  },
  {
    id: 'log_3',
    pipelineRunId: 'run_demo_104',
    level: 'WARN',
    message: 'Webhook signature secret STRIPE_WEBHOOK_SECRET missing in test environment',
    timestamp: new Date(Date.now() - 1.97 * 3600 * 1000).toISOString(),
  },
  {
    id: 'log_4',
    pipelineRunId: 'run_demo_104',
    level: 'ERROR',
    message:
      'SignatureVerificationException: No valid signature found matching timestamp=1722800000',
    timestamp: new Date(Date.now() - 1.96 * 3600 * 1000).toISOString(),
  },
  {
    id: 'log_5',
    pipelineRunId: 'run_demo_104',
    level: 'ERROR',
    message: 'Process exited with status 1 — Test suite failed (1 failed, 14 passed)',
    timestamp: new Date(Date.now() - 1.95 * 3600 * 1000).toISOString(),
  },
];

export const DEMO_DEPLOYMENTS: Deployment[] = [
  {
    id: 'dep_demo_1',
    environment: 'production',
    status: 'ACTIVE',
    version: 'v2.4.0',
    imageTag: 'stockflow-backend:v2.4.0',
    deployedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    health: 'healthy',
    url: 'https://stockflow.opspilot.app',
  },
  {
    id: 'dep_demo_2',
    environment: 'production',
    status: 'ACTIVE',
    version: 'v3.1.2',
    imageTag: 'frontend-next:v3.1.2',
    deployedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    health: 'healthy',
    url: 'https://app.opspilot.io',
  },
  {
    id: 'dep_demo_3',
    environment: 'staging',
    status: 'ACTIVE',
    version: 'v2.5.0-rc2',
    imageTag: 'stockflow-backend:v2.5.0-rc2',
    deployedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    health: 'healthy',
    url: 'https://staging.stockflow.opspilot.app',
  },
  {
    id: 'dep_demo_4',
    environment: 'preview',
    status: 'ROLLED_BACK',
    version: 'v2.5.0-rc1',
    imageTag: 'stockflow-backend:v2.5.0-rc1',
    deployedAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    rolledBackAt: new Date(Date.now() - 17.5 * 3600 * 1000).toISOString(),
    health: 'unhealthy',
    url: 'https://pr-104.preview.opspilot.app',
  },
];

export const DEMO_AI_REPORTS = [
  {
    id: 'rpt_demo_1',
    organizationId: 'org_demo_acme',
    projectId: 'proj_demo_stockflow',
    type: 'ROOT_CAUSE_ANALYSIS',
    targetId: 'run_demo_104',
    summary: 'Stripe Webhook Signature Verification Failure in Integration Stage',
    rootCause:
      'The environment variable STRIPE_WEBHOOK_SECRET is not bound in the integration test container specification, causing SignatureVerificationException during mock event processing.',
    confidenceScore: 0.96,
    riskLevel: 'HIGH',
    recommendations: [
      'Add STRIPE_WEBHOOK_SECRET to project secrets in OpsPilot Secrets Manager.',
      'Inject secret into integration stage runner via .opspilot.yaml environment bindings.',
      'Re-run pipeline run #run_demo_104 to verify fix.',
    ],
    createdAt: new Date(Date.now() - 1.9 * 3600 * 1000).toISOString(),
  },
];

export const DEMO_ARTIFACTS: Artifact[] = [
  {
    id: 'art_demo_1',
    name: 'stockflow-backend-dist-v2.4.0.tar.gz',
    pipelineRunId: 'run_demo_102',
    size: 2458900,
    sha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    mimeType: 'application/gzip',
    createdAt: new Date(Date.now() - 14.5 * 60 * 1000).toISOString(),
    downloadUrl: '#',
  },
  {
    id: 'art_demo_2',
    name: 'coverage-report.html',
    pipelineRunId: 'run_demo_103',
    size: 489200,
    sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    mimeType: 'text/html',
    createdAt: new Date(Date.now() - 41.5 * 60 * 1000).toISOString(),
    downloadUrl: '#',
  },
];

export const DEMO_SECRETS: Secret[] = [
  {
    id: 'sec_demo_1',
    key: 'DATABASE_URL',
    description: 'Production PostgreSQL Connection String (Encrypted with AES-256-GCM)',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'sec_demo_2',
    key: 'STRIPE_WEBHOOK_SECRET',
    description: 'Stripe Webhook Signature Validation Key',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'sec_demo_3',
    key: 'OPENAI_API_KEY',
    description: 'AI Engine Vector & Analysis Key',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'sec_demo_4',
    key: 'GITHUB_WEBHOOK_SECRET',
    description: 'HMAC Webhook Ingestion Secret',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
];

export function isDemoMode(): boolean {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem('opspilot_demo_mode') === 'true';
}

export function enableDemoMode(): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem('opspilot_token', 'demo_token_sec_key_998877');
  localStorage.setItem('opspilot_user', JSON.stringify(DEMO_USER));
  localStorage.setItem('opspilot_demo_mode', 'true');
}

export function disableDemoMode(): void {
  if (typeof window === 'undefined') return;
  localStorage.removeItem('opspilot_demo_mode');
}
