import { PipelineRun, PipelineDefinition, SystemHealth, Deployment } from './apiClient';

export const DEMO_USER = {
  id: 'demo-user-123',
  email: 'demo@opspilot.io',
  name: 'Sarah Chen (Demo)',
  role: 'ADMIN',
  isSuperAdmin: true,
  isDemo: true,
};

export const DEMO_SYSTEM_HEALTH: SystemHealth = {
  totalOrganizations: 3,
  totalProjects: 12,
  totalEnvironments: 4,
  totalPipelineDefinitions: 7,
  totalPipelineRuns: 148,
  totalDeployments: 42,
  deploymentSuccessRate: 98.4,
};

export const DEMO_PIPELINES: PipelineDefinition[] = [
  {
    id: 'demo-pip-1',
    projectId: 'demo-project-id',
    name: 'stockflow-backend',
    slug: 'stockflow-backend',
    description: 'Core microservices backend API (Node.js/NestJS)',
    triggerType: 'WEBHOOK',
    triggerBranch: 'main',
    isActive: true,
    currentVersionNumber: 14,
    repositoryUrl: 'https://github.com/opspilot-org/stockflow-api',
    branch: 'main',
    status: 'SUCCESS',
    lastRunAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    successRate: 98.2,
    totalRuns: 64,
  },
  {
    id: 'demo-pip-2',
    projectId: 'demo-project-id',
    name: 'opspilot-ai-service',
    slug: 'opspilot-ai-service',
    description: 'AI Root Cause Analysis & Log Parsing Engine',
    triggerType: 'WEBHOOK',
    triggerBranch: 'main',
    isActive: true,
    currentVersionNumber: 8,
    repositoryUrl: 'https://github.com/opspilot-org/ai-analysis-service',
    branch: 'main',
    status: 'RUNNING',
    lastRunAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    successRate: 100,
    totalRuns: 28,
  },
  {
    id: 'demo-pip-3',
    projectId: 'demo-project-id',
    name: 'frontend-next',
    slug: 'frontend-next',
    description: 'Next.js 16 Web Application UI',
    triggerType: 'WEBHOOK',
    triggerBranch: 'main',
    isActive: true,
    currentVersionNumber: 22,
    repositoryUrl: 'https://github.com/opspilot-org/frontend-next',
    branch: 'main',
    status: 'SUCCESS',
    lastRunAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    successRate: 96.5,
    totalRuns: 31,
  },
  {
    id: 'demo-pip-4',
    projectId: 'demo-project-id',
    name: 'payments-worker',
    slug: 'payments-worker',
    description: 'Stripe & Webhook Event Processing Queue',
    triggerType: 'MANUAL',
    triggerBranch: 'feat/stripe-v3',
    isActive: true,
    currentVersionNumber: 5,
    repositoryUrl: 'https://github.com/opspilot-org/payments-worker',
    branch: 'feat/stripe-v3',
    status: 'FAILED',
    lastRunAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    successRate: 85.0,
    totalRuns: 12,
  },
  {
    id: 'demo-pip-5',
    projectId: 'demo-project-id',
    name: 'auth-gateway',
    slug: 'auth-gateway',
    description: 'OAuth2 & JWT Authentication Gateway (Rust)',
    triggerType: 'WEBHOOK',
    triggerBranch: 'main',
    isActive: true,
    currentVersionNumber: 11,
    repositoryUrl: 'https://github.com/opspilot-org/auth-gateway',
    branch: 'main',
    status: 'SUCCESS',
    lastRunAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    successRate: 100,
    totalRuns: 13,
  },
];

export const DEMO_RUNS: PipelineRun[] = [
  {
    id: 'run_demo_101',
    pipelineDefinitionId: 'demo-pip-1',
    status: 'RUNNING',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: 'e4f92a189c',
    branch: 'main',
    startedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 2.5 * 60 * 1000).toISOString(),
    durationSeconds: 45,
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    pipelineName: 'stockflow-backend',
    repositoryUrl: 'https://github.com/opspilot-org/stockflow-api',
  },
  {
    id: 'run_demo_102',
    pipelineDefinitionId: 'demo-pip-2',
    status: 'SUCCESS',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: '8b3c1d904e',
    branch: 'main',
    startedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 14.5 * 60 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 15.2 * 60 * 1000).toISOString(),
    durationSeconds: 32,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    pipelineName: 'opspilot-ai-service',
    repositoryUrl: 'https://github.com/opspilot-org/ai-analysis-service',
  },
  {
    id: 'run_demo_103',
    pipelineDefinitionId: 'demo-pip-3',
    status: 'SUCCESS',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: 'f371b45aa2',
    branch: 'main',
    startedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 41.5 * 60 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 42.2 * 60 * 1000).toISOString(),
    durationSeconds: 28,
    createdAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    pipelineName: 'frontend-next',
    repositoryUrl: 'https://github.com/opspilot-org/frontend-next',
  },
  {
    id: 'run_demo_104',
    pipelineDefinitionId: 'demo-pip-4',
    status: 'FAILED',
    triggerType: 'MANUAL',
    triggeredBy: 'Sarah Chen',
    commitSha: 'a345242ff1',
    branch: 'feat/stripe-v3',
    startedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 1.95 * 3600 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 2.01 * 3600 * 1000).toISOString(),
    durationSeconds: 18,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    pipelineName: 'payments-worker',
    repositoryUrl: 'https://github.com/opspilot-org/payments-worker',
  },
  {
    id: 'run_demo_105',
    pipelineDefinitionId: 'demo-pip-5',
    status: 'SUCCESS',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: '7c9e01fb4a',
    branch: 'main',
    startedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 4.9 * 3600 * 1000).toISOString(),
    queuedAt: new Date(Date.now() - 5.01 * 3600 * 1000).toISOString(),
    durationSeconds: 24,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    pipelineName: 'auth-gateway',
    repositoryUrl: 'https://github.com/opspilot-org/auth-gateway',
  },
  {
    id: 'run_demo_106',
    pipelineDefinitionId: 'demo-pip-1',
    status: 'SUCCESS',
    triggerType: 'WEBHOOK',
    triggeredBy: 'github-webhook',
    commitSha: '5b2d8e411c',
    branch: 'main',
    startedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 7.9 * 3600 * 1000).toISOString(),
    durationSeconds: 39,
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    pipelineName: 'stockflow-backend',
    repositoryUrl: 'https://github.com/opspilot-org/stockflow-api',
  },
  {
    id: 'run_demo_107',
    pipelineDefinitionId: 'demo-pip-2',
    status: 'QUEUED',
    triggerType: 'SCHEDULED',
    triggeredBy: 'cron-job',
    commitSha: '9d1f3b2077',
    branch: 'staging',
    queuedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    pipelineName: 'opspilot-ai-service',
    repositoryUrl: 'https://github.com/opspilot-org/ai-analysis-service',
  },
];

export const DEMO_DEPLOYMENTS: Deployment[] = [
  {
    id: 'dep_demo_1',
    environment: 'production',
    status: 'ACTIVE',
    version: 'v2.4.0',
    imageTag: 'stockflow:v2.4.0',
    deployedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    health: 'healthy',
    url: 'https://stockflow.opspilot.app',
  },
  {
    id: 'dep_demo_2',
    environment: 'production',
    status: 'ACTIVE',
    version: 'v3.1.2',
    imageTag: 'frontend-next:v3.1.2',
    deployedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    health: 'healthy',
    url: 'https://app.opspilot.io',
  },
  {
    id: 'dep_demo_3',
    environment: 'staging',
    status: 'ACTIVE',
    version: 'v2.5.0-rc2',
    imageTag: 'stockflow:v2.5.0-rc2',
    deployedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    health: 'healthy',
    url: 'https://staging.stockflow.opspilot.app',
  },
  {
    id: 'dep_demo_4',
    environment: 'preview',
    status: 'ROLLED_BACK',
    version: 'v2.5.0-rc1',
    imageTag: 'stockflow:v2.5.0-rc1',
    deployedAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    rolledBackAt: new Date(Date.now() - 17.5 * 3600 * 1000).toISOString(),
    health: 'unhealthy',
    url: 'https://pr-104.preview.opspilot.app',
  },
];

export function isDemoMode(): boolean {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem('opspilot_demo_mode') === 'true';
}

export function enableDemoMode(): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem('opspilot_token', 'demo_token_sec_key_998877');
  localStorage.setItem('opspilot_user', JSON.stringify(DEMO_USER));
  localStorage.setItem('opspilot_demo_mode', 'true');
}

export function disableDemoMode(): void {
  if (typeof window === 'undefined') return;
  localStorage.removeItem('opspilot_demo_mode');
}
